FROM parana/php-7-apache
#
# parana/php-7-apache usa a versão 8 do Debian de codinome Jessie
#
MAINTAINER João Antonio Ferreira "joao.parana@gmail.com"

ENV REFRESHED_AT 2017-02-14

ENV GET_SIMPLE_CMS_HOME /var/www/site

# instalando as extensões PHP que precisaremos
RUN apt-get update \
  && apt-get install -y git

CMD [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND" ]
